# Generated by Django 3.0.7 on 2020-06-27 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='subject',
            new_name='title',
        ),
    ]
